name: Test Project
on: push
jobs:
  auto-test: 
    runs-on: ubuntu-latest
    steps: 
    - name: Pull to runner
      uses: actions/checkout@v3
      
    - name: Install nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies    
      run: npm ci

    - name: Run test    
      run: npm test
      
  deploy:
    needs: auto-test
    runs-on: ubuntu-latest
    steps:
    - name: Pull to runner
      uses: actions/checkout@v3
      
    - name: Install nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies    
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy
      run: echo "Deploy dummy!!!!"
